# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jwoo <jwoo@student.42seoul.kr>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/03/09 02:28:13 by minckim           #+#    #+#              #
#    Updated: 2021/05/28 21:25:28 by jwoo             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all : name

name : random_numbers

random_numbers : random_numbers.cpp
	clang++ random_numbers.cpp --std=c++11 -o random_numbers

fclean:
	rm -rf random_numbers